CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_INSERTAR_USUARIO`(
IN PV_NOMBRE VARCHAR(150),
IN PV_APELLIDO VARCHAR(150),
IN PV_CELULAR VARCHAR(8),
IN PC_SEXO CHAR(1),
IN PV_NUMERO_IDENTIDAD VARCHAR(13),
IN PV_NOMBRE_USUARIO VARCHAR(20),
IN PV_CONTRASENA VARCHAR(30),
OUT PV_MENSAJE VARCHAR(2000) 
)
SP: BEGIN
	DECLARE VD_FECHA_INGRESO DATETIME DEFAULT NOW();
    DECLARE VD_ID_ROL_USUARIO INT DEFAULT 1;
    DECLARE VN_IDPERSONA INT;
    
    /*Manejador de excepciones*/
     DECLARE EXIT HANDLER FOR SQLEXCEPTION
        BEGIN
            SHOW ERRORS LIMIT 1;
            SET PV_MENSAJE = CONCAT('Ocurrió un error.');
            ROLLBACK;
        END;


    /* Validación de parámetros que no deben ser nulos */
    
    CALL SP_VALIDACION_NULOS(PV_NOMBRE, 'Nombre', PV_MENSAJE);
    IF PV_MENSAJE IS NOT NULL THEN 
        LEAVE SP;
    END IF;
    
    CALL SP_VALIDACION_NULOS(PV_APELLIDO, 'Apellido', PV_MENSAJE);
    IF PV_MENSAJE IS NOT NULL THEN 
        LEAVE SP;
    END IF;
    
    CALL SP_VALIDACION_NULOS(PV_CELULAR, 'Celular', PV_MENSAJE);
    IF PV_MENSAJE IS NOT NULL THEN 
        LEAVE SP;
    END IF;
    
    CALL SP_VALIDACION_NULOS(PC_SEXO, 'Sexo', PV_MENSAJE);
    IF PV_MENSAJE IS NOT NULL THEN 
        LEAVE SP;
    END IF;
    
    CALL SP_VALIDACION_NULOS(PV_NOMBRE_USUARIO, 'Nombre de Usuario', PV_MENSAJE);
    IF PV_MENSAJE IS NOT NULL THEN 
        LEAVE SP;
    END IF;
    
	CALL SP_VALIDACION_NULOS(PV_NUMERO_IDENTIDAD, 'Número de identidad', PV_MENSAJE);
    IF PV_MENSAJE IS NOT NULL THEN 
        LEAVE SP;
    END IF;
    
    CALL SP_VALIDACION_NULOS(PV_CONTRASENA, 'Contraseña', PV_MENSAJE);
    IF PV_MENSAJE IS NOT NULL THEN 
        LEAVE SP;
    END IF;
    
    /* Validación de repetidos */
    
    IF EXISTS (SELECT '' FROM Usuario WHERE NOMBRE_USUARIO = PV_NOMBRE_USUARIO ) THEN
		SET PV_MENSAJE = 'El nombre de usuario ya existe';
        LEAVE SP;
    END IF;
    
    IF EXISTS (SELECT '' FROM Persona WHERE Numero_Identidad = PV_NUMERO_IDENTIDAD ) THEN
		SET PV_MENSAJE = 'La identidad está asociada a otra persona verificada';
		LEAVE SP;
	END IF;
    
    /* Insertar Persona */
    INSERT INTO Persona(NOMBRE, APELLIDOS, CELULAR, SEXO, NUMERO_IDENTIDAD) VALUES (PV_NOMBRE, PV_APELLIDO, PV_CELULAR, PC_SEXO, PV_NUMERO_IDENTIDAD);
    SET VN_IDPERSONA = (SELECT LAST_INSERT_ID());
  
  /* Insertar Usuario */
	INSERT INTO Usuario(NOMBRE_USUARIO, FECHA_INGRESO, CONTRASENA, FOTO_PERFIL, PERSONA_IDPERSONA) VALUES (PV_NOMBRE_USUARIO, VD_FECHA_INGRESO, 
    PV_CONTRASENA, NULL, VN_IDPERSONA);
END
