CREATE DEFINER=`root`@`localhost` PROCEDURE `SP_VALIDACION_NULOS`(IN VALOR VARCHAR(200), IN NOMBRE_PARAMETRO VARCHAR(200), OUT MENSAJE VARCHAR(1000))
BEGIN
	IF VALOR IS NULL OR VALOR = '' THEN
		SET MENSAJE = CONCAT('El parámetro ', NOMBRE_PARAMETRO, ' es nulo.');
    END IF;
END
